### ISSUE TITLE
Management Overview

### ISSUE THREAD

**Issue by DaGeRe** [jenkinsci/peass-ci-plugin#61]
Besides the day-to-day information over performance changes, an overview over long-term-changes might be helpful. This should show the changes per test case for a given time span, e.g. since a given release tag.

**Comment by DaGeRe** [comment]
The basic implementation of this requirement would require the following steps:

- [ ] Create basic data structure and dummy builder
- [ ] Create overview UI in jelly
- [ ] Read data from cache (and create example cache data for unit test)

**Comment by DaGeRe** [comment]
The basic data structure and the dummy builder are now existing: e0c337f660b7e80786d62e31a2b038930b1feccd Next step would be to implement the details.

**Comment by DaGeRe** [comment]
This works now (with `peassOverview`): https://github.com/jenkinsci/peass-ci-plugin/blob/main/src/main/resources/de/dagere/peass/ci/peassOverview/PeassOverviewBuilder/config.jelly 

Sortability is not required by now. Please file new issues for feature enhancement requests.
